import time
while True:
    print("wavey")
    time.sleep(0.25)
    print(" wavey")
    time.sleep(0.25)
    print("   wavey")
    time.sleep(0.25)
    print("       wavey")
    time.sleep(0.25)
    print("         wavey")
    time.sleep(0.25)
    print("          wavey")
    time.sleep(0.25)
    print("         wavey")
    time.sleep(0.25)
    print("       wavey")
    time.sleep(0.25)
    print("   wavey")
    time.sleep(0.25)
    print(" wavey")
    time.sleep(0.25) 