import time
while True:
    print("wavey")
    time.sleep(0.05)
    print(" wavey")
    time.sleep(0.05)
    print("   wavey")
    time.sleep(0.05)
    print("       wavey")
    time.sleep(0.05)
    print("         wavey")
    time.sleep(0.05)
    print("          wavey")
    time.sleep(0.05)
    print("         wavey")
    time.sleep(0.05)
    print("       wavey")
    time.sleep(0.05)
    print("   wavey")
    time.sleep(0.05)
    print(" wavey")
    time.sleep(0.05) 